# Generated by Django 4.1.4 on 2022-12-22 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('releaseDate', models.DateField()),
                ('rentDate', models.DateField(default=datetime.datetime(2022, 12, 22, 9, 25, 52, 735529, tzinfo=datetime.timezone.utc))),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.studio')),
            ],
        ),
    ]
